@host = cont-staffingsvc.jollybush-3d99f517.northeurope.azurecontainerapps.io/
@port = 61843

GET https://localhost:{{port}}/v1.0/invoke/staffingsvc/method/employees HTTP/1.1

###
GET http://localhost:{{port}}/v1.0/invoke/staffingsvc/method/employees/3054e863-1de0-438d-b103-7086c6d7c109 HTTP/1.1

###
POST http://localhost:{{port}}/v1.0-alpha1/state/staffing/query HTTP/1.1
Content-Type: application/json

{
    "query": {    }
}

###
DELETE http://localhost:{{port}}/v1.0/invoke/staffingsvc/method/employees/a8241c85-32e6-4fbe-ad32-2a228d3a6eda HTTP/1.1 

###
POST http://localhost:{{port}}/v1.0/invoke/staffingsvc/method/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Roel",
    "lastName": "van de Grint",
    "joinedOn": "2017-09-01",
    "picture": "IMG_0609.JPG"
}

###
POST http://localhost:{{port}}/v1.0/invoke/staffingsvc/method/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Donald",
    "lastName": "Hessing",
    "joinedOn": "1928-03-01T00:00:00Z",
    "picture": "Donald.png"
}

###
POST http://localhost:{{port}}/v1.0/invoke/staffingsvc/method/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Gerben",
    "lastName": "de Vries",
    "joinedOn": "2021-06-06T00:00:00Z"
}

