apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: events
spec:
  # type: pubsub.azure.servicebus
  type: pubsub.redis
  version: v1
  metadata:
  # - name: redisHost
  #   value: 20.105.17.191:6379
  # - name: redisPassword
  #   value: "p@ss$12E45"
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
