apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: staffing
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 20.105.17.191:6379
  - name: redisPassword
    value: "p@ss$12E45"
