apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        dapr.io/app-id: frontend
        dapr.io/app-port: '80'
        dapr.io/enabled: 'true'
        dapr.io/config: 'appconfig'
    spec:
      containers:
      - name: frontend
        image: roelvandegrint.azurecr.io/cluster_demo_frontend:0.1.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
